services:
  tests:
    image: buildkite/plugin-tester:v4.2.0
    volumes:
      - ".:/plugin"
  lint:
    image: buildkite/plugin-linter:v2.1.0
    command: ['--id', 'wiz']
    volumes:
      - ".:/plugin"
