steps:
  - label: ":sparkles: Lint"
    plugins:
      - plugin-linter#v3.3.0:
          id: wiz

  - label: ":shell: Shellcheck"
    plugins:
      - shellcheck#v1.4.0:
          files:
            - hooks/**
            - lib/**

  - label: ":shell: Tests"
    plugins:
      - plugin-tester#v1.2.0:
          folders:
            - tests
