#!/usr/bin/env bash

set -euo pipefail

DIR="$(cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd)"

# shellcheck source=lib/plugin.bash
. "$DIR/../lib/plugin.bash"

# shellcheck source=lib/shared.bash
. "$DIR/../lib/shared.bash"

SCAN_TYPE="${BUILDKITE_PLUGIN_WIZ_SCAN_TYPE:-}"
FILE_PATH="${BUILDKITE_PLUGIN_WIZ_PATH:-}"

if [[ -z "${SCAN_TYPE}" ]]; then
    echo "+++ 🚨 Missing scan type. Possible values: 'iac', 'docker', 'dir'"
    exit 1
fi

if [[ "${SCAN_TYPE}" == "docker" && -z "${BUILDKITE_PLUGIN_WIZ_IMAGE_ADDRESS:-}" ]]; then
    echo "+++ 🚨 Missing image address, docker scans require an address to pull the image"
    exit 1
fi

validate_wiz_client_credentials

declare -a cli_args
# shellcheck disable=SC2207
cli_args=($(build_wiz_cli_args "${SCAN_TYPE}"))
wiz_cli_container_image=$(detect_wiz_cli_container)

case "${SCAN_TYPE}" in
iac)
    iac_scan "$wiz_cli_container_image" "${FILE_PATH}" "${cli_args[@]}"
    ;;
docker)
    docker_image_scan "$wiz_cli_container_image" "${BUILDKITE_PLUGIN_WIZ_IMAGE_ADDRESS}" "${cli_args[@]}"
    ;;
dir)
    dir_scan "$wiz_cli_container_image" "${FILE_PATH}" "${cli_args[@]}"
    ;;
esac
